requires 'perl', '5.016';
requires 'Plack', '1.0047';
requires 'Moose';
requires 'LWP::UserAgent', '== 6.72';
requires 'Try::Tiny', '>= 0.30, < 1';
requires 'List::Util', '1.45';
requires 'Exporter';
requires 'JSON::MaybeXS', '== 1.004005';
recommends 'JSON::XS';
suggests 'Net::DNS';
requires 'Acme::Git', git => 'https://github.com/acme/p5-acme-git.git', ref => 'main';

on 'test' => sub {
    requires 'Test::More', '0.98';
    requires 'Test::Deep';
};

on develop => sub {
    requires 'Perl::Critic';
};

feature 'sqlite', 'SQLite support' => sub {
    requires 'DBD::SQLite';
};
