package cpp

import (
	"reflect"
	"strings"
	"testing"

	"github.com/sarumaj/depphunter-cli/internal/lang"
	"github.com/sarumaj/depphunter-cli/internal/lang/langtest"
)

// testdata/repo: a CMake-style project whose build/compile_commands.json gives
// src/main.cpp (an "arguments" entry) and lib/util.c (a "command" entry) their
// include paths; headers under include/, lib/include/, a second util/util.h under
// legacy/ that only the database tells apart, a library under libs/ found by the
// end of its path, a vendored fmt under third_party/, and a stray tests/stdio.h.
func analyze(t *testing.T) map[string]*lang.FileResult {
	t.Helper()
	return langtest.Analyze(t, Plugin{}, "testdata/repo")
}

func std(eco, pkg string) lang.Target { return lang.Target{Ecosystem: eco, Package: pkg} }

func external(pkg string) lang.Target {
	return lang.Target{Ecosystem: ecoExternal, Package: pkg, Unresolved: true}
}

// Verifies: REQ-CPP-002, REQ-CPP-004, REQ-CPP-005, REQ-CPP-006, REQ-CPP-007
func TestIncludes(t *testing.T) {
	// cSpell: disable
	langtest.CheckImports(t, analyze(t)["src/main.cpp"], map[string]lang.Target{
		// Beside the includer.
		`#include "local.h"`: {Local: "src/local.h"},
		// On the include path of the file's compile_commands.json entry: -I, -isystem.
		`#include "app/app.hpp"`:  {Local: "include/app/app.hpp"},
		`#include <fmt/core.h>`:   {Local: "third_party/fmt/include/fmt/core.h"},
		`#include "net/socket.h"`: {Local: "libs/net/net/socket.h"}, // the only file so ending
		`#include <map>`:          std(ecoCppStd, "map"),
		`#include <vector>`:       std(ecoCppStd, "vector"),
		`#include <cstdint>`:      std(ecoCppStd, "cstdint"),
		// Not tests/stdio.h: a system header is not shadowed by a file of that name.
		`#include <stdio.h>`:        std(ecoCStd, "stdio.h"),
		`#include <sys/socket.h>`:   std(ecoSystem, "sys/socket.h"),
		`#include <pthread.h>`:      std(ecoSystem, "pthread.h"),
		`#include <windows.h>`:      std(ecoSystem, "windows.h"),
		`#include <boost/asio.hpp>`: external("boost"),
		`#include <openssl/ssl.h>`:  external("openssl"),
		`#include <zlib.h>`:         external("zlib"),
		`#include "gtest/gtest.h"`:  external("gtest"),
		// Generated by the build: nothing to name.
		`#include "config.h"`: {},
		// Not captured: an include through a macro, in a comment, in #if 0, and in the
		// #else of #if 1.
	})
	// The "command" entry's -I tells lib/include/util/util.h from legacy/util/util.h.
	langtest.CheckImports(t, analyze(t)["lib/util.c"], map[string]lang.Target{
		`#include "util/util.h"`: {Local: "lib/include/util/util.h"},
		`#include <stdlib.h>`:    std(ecoCStd, "stdlib.h"),
	})
	// A header has no entry of its own and is given every entry's include path.
	langtest.CheckImports(t, analyze(t)["include/app/app.hpp"], map[string]lang.Target{
		`#include "detail.hpp"`: {Local: "include/app/detail.hpp"},
		`#include <string>`:     std(ecoCppStd, "string"),
	})
	// cSpell: enable
}

// Without a compilation database, include/, src/ and the root are searched.
//
// Verifies: REQ-CPP-004
func TestConventionalDirs(t *testing.T) {
	r := newResolver(t.TempDir(), langtest.Files(t, "testdata/repo"))
	for spec, want := range map[lang.RawImport]lang.Target{
		{Module: "app/detail.hpp", Name: bracket}: {Local: "include/app/detail.hpp"},
		{Module: "local.h", Name: bracket}:        {Local: "src/local.h"},
		{Module: "lib/util.c", Name: quoted}:      {Local: "lib/util.c"},
		// Two files end in util/util.h: the one sharing lib/ with the includer wins.
		{Module: "util/util.h", Name: quoted}:          {Local: "lib/include/util/util.h"},
		{Module: "/usr/include/stdio.h", Name: quoted}: {},
	} {
		if got := r.Resolve("lib/util.c", spec); got != want {
			t.Errorf("%s: got %+v, want %+v", spec.Module, got, want)
		}
	}
	if got := r.Resolve("src/main.cpp", lang.RawImport{Module: "util/util.h", Name: bracket}); got != external("util") {
		t.Errorf("an include two files end in, neither nearer: got %+v", got)
	}
}

// Verifies: REQ-CPP-004
func TestIncludeDirs(t *testing.T) {
	for _, tc := range []struct {
		args []string
		want []string
	}{
		{[]string{"g++", "-Ia", "-I", "b", "-iquote", "c", "-isystem=d", "-idirafter", "e", "-include", "f.h", "/Ix"}, []string{"a", "b", "c", "=d", "e"}},
		{[]string{`C:\VS\bin\cl.exe`, "/Ia", "/I", "b", "/external:Ic", "-Id"}, []string{"a", "b", "c", "d"}},
	} {
		if got := includeDirs(tc.args); !reflect.DeepEqual(got, tc.want) {
			t.Errorf("%v: got %v, want %v", tc.args, got, tc.want)
		}
	}
}

// Verifies: REQ-CPP-002, REQ-CPP-007
func TestPreprocess(t *testing.T) {
	src := strings.Join([]string{
		`#include "a.h" /* a comment "with quotes" */`,
		`char *s = "/* not a comment";`,
		`#include <b.h>`,
		`#if 0 // off`,
		`#include "c.h"`,
		`#elif defined(X)`,
		`#include "d.h"`,
		`#endif`,
		`#define LONG \`,
		`  #include "e.h"`,
		`#include_next <f.h>`,
		`#import <Foundation/Foundation.h>`,
	}, "\n")
	includes, dead := preprocess([]byte(src))
	var got []string
	for _, im := range includes {
		got = append(got, im.Spec)
	}
	want := []string{`#include "a.h"`, `#include <b.h>`, `#include "d.h"`, `#include_next <f.h>`}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("includes: got %q, want %q", got, want)
	}
	if !dead[5] || dead[7] || dead[3] {
		t.Errorf("dead lines: %v", dead)
	}
}

// Verifies: REQ-CPP-003
func TestSymbols(t *testing.T) {
	res := analyze(t)
	langtest.CheckSymbols(t, res["include/app/app.hpp"], map[string]string{
		"APP_VERSION": "macro", "APP_MAX": "macro", "app": "namespace",
		"Server": "class", "Server.Server": "method", "Server.~Server": "method", "Server.start": "method",
		"Server.port": "method", "Server.operator==": "method", "Server.Options": "struct",
		"Mode": "enum", "Value": "union", "Name": "type", "Id": "type", "twice": "func", "parse": "func",
	})
	// Out-of-class definitions belong to their class; a prototype of a function the
	// file defines is not a second symbol; nothing in a function body or #if 0 is one,
	// nor a test macro's body.
	langtest.CheckSymbols(t, res["src/main.cpp"], map[string]string{
		"ALIVE": "macro", "app": "namespace", "Server.Server": "method", "Server.~Server": "method",
		"Server.start": "method", "helper": "func", "Point": "struct", "callback_t": "type", "main": "func",
	})
	langtest.CheckSymbols(t, res["include/app/detail.hpp"], map[string]string{"app.detail": "namespace", "answer": "func"})
	// C with the C grammar, where "new" is a name.
	langtest.CheckSymbols(t, res["lib/util.c"], map[string]string{"buffer": "struct", "split": "func", "util_count": "func"})
	// A C header read by the C++ grammar; its guard is no symbol.
	langtest.CheckSymbols(t, res["lib/include/util/util.h"], map[string]string{
		"util_list": "struct", "util_list_t": "type", "util_count": "func",
	})
}

// Verifies: REQ-CPP-001
func TestClaims(t *testing.T) {
	res := analyze(t)
	for _, p := range []string{"src/main.cpp", "lib/util.c", "include/app/app.hpp", "tests/stdio.h"} {
		if res[p] == nil {
			t.Errorf("%s not analyzed", p)
		}
	}
	if res["build/compile_commands.json"] != nil {
		t.Error("compile_commands.json analyzed")
	}
}

// Verifies: REQ-CPP-005
func TestStandard(t *testing.T) {
	for name, want := range map[string]string{
		"vector": ecoCppStd, "cstdio": ecoCppStd, "experimental/filesystem": ecoCppStd, "bits/stdc++.h": ecoCppStd,
		"stdio.h": ecoCStd, "threads.h": ecoCStd, "unistd.h": ecoSystem, "sys/types.h": ecoSystem,
		"linux/fs.h": ecoSystem, "Windows.h": ecoSystem, "TargetConditionals.h": ecoSystem, "ext/stdio_filebuf.h": ecoCppStd, "CoreFoundation/CoreFoundation.h": ecoSystem, "immintrin.h": ecoSystem,
		"boost/asio.hpp": "", "curl/curl.h": "", "vector.h": "",
	} {
		if got := standard(name); got != want {
			t.Errorf("%s: got %q, want %q", name, got, want)
		}
	}
}
