package cpp

import (
	"os"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/sarumaj/depphunter-cli/internal/lang"
	"github.com/sarumaj/depphunter-cli/internal/lang/langtest"
	"github.com/sarumaj/depphunter-cli/internal/scan"
)

// testdata/repo: a CMake-style project whose build/compile_commands.json gives
// src/main.cpp (an "arguments" entry) and lib/util.c (a "command" entry) their
// include paths; headers under include/, lib/include/, a second util/util.h under
// legacy/ that only the database tells apart, a library under libs/ found by the
// end of its path, a vendored fmt under third_party/, and a stray tests/stdio.h.
func analyze(t *testing.T) map[string]*lang.FileResult {
	t.Helper()
	return langtest.Analyze(t, Plugin{}, "testdata/repo")
}

func std(ecosystem, packageName string) lang.Target {
	return lang.Target{Ecosystem: ecosystem, Package: packageName}
}

func external(packageName string) lang.Target {
	return lang.Target{Ecosystem: ecosystemExternal, Package: packageName, Unresolved: true}
}

// Verifies: REQ-CPP-002, REQ-CPP-004, REQ-CPP-005, REQ-CPP-006, REQ-CPP-007
func TestIncludes(t *testing.T) {
	// cSpell: disable
	langtest.CheckImports(t, analyze(t)["src/main.cpp"], map[string]lang.Target{
		// Beside the includer.
		`#include "local.h"`: {Local: "src/local.h"},
		// On the include path of the file's compile_commands.json entry: -I, -isystem.
		`#include "app/app.hpp"`:  {Local: "include/app/app.hpp"},
		`#include <fmt/core.h>`:   {Local: "third_party/fmt/include/fmt/core.h"},
		`#include "net/socket.h"`: {Local: "libs/net/net/socket.h"}, // the only file so ending
		`#include <map>`:          std(ecosystemCppStd, "map"),
		`#include <vector>`:       std(ecosystemCppStd, "vector"),
		`#include <cstdint>`:      std(ecosystemCppStd, "cstdint"),
		// Not tests/stdio.h: a system header is not shadowed by a file of that name.
		`#include <stdio.h>`:        std(ecosystemCStd, "stdio.h"),
		`#include <sys/socket.h>`:   std(ecosystemSystem, "sys/socket.h"),
		`#include <pthread.h>`:      std(ecosystemSystem, "pthread.h"),
		`#include <windows.h>`:      std(ecosystemSystem, "windows.h"),
		`#include <boost/asio.hpp>`: external("boost"),
		`#include <openssl/ssl.h>`:  external("openssl"),
		`#include <zlib.h>`:         external("zlib"),
		`#include "gtest/gtest.h"`:  external("gtest"),
		// Generated by the build: nothing to name.
		`#include "config.h"`: {},
		// Not captured: an include through a macro, in a comment, in #if 0, and in the
		// #else of #if 1.
	})
	// The "command" entry's -I tells lib/include/util/util.h from legacy/util/util.h.
	langtest.CheckImports(t, analyze(t)["lib/util.c"], map[string]lang.Target{
		`#include "util/util.h"`: {Local: "lib/include/util/util.h"},
		`#include <stdlib.h>`:    std(ecosystemCStd, "stdlib.h"),
	})
	// A header has no entry of its own and is given every entry's include path.
	langtest.CheckImports(t, analyze(t)["include/app/app.hpp"], map[string]lang.Target{
		`#include "detail.hpp"`: {Local: "include/app/detail.hpp"},
		`#include <string>`:     std(ecosystemCppStd, "string"),
	})
	// cSpell: enable
}

// Without a compilation database, include/, src/ and the root are searched.
//
// Verifies: REQ-CPP-004
func TestConventionalDirectories(t *testing.T) {
	r := newResolver(t.TempDir(), langtest.Files(t, "testdata/repo"))
	for spec, want := range map[lang.RawImport]lang.Target{
		{Module: "app/detail.hpp", Name: bracket}: {Local: "include/app/detail.hpp"},
		{Module: "local.h", Name: bracket}:        {Local: "src/local.h"},
		{Module: "lib/util.c", Name: quoted}:      {Local: "lib/util.c"},
		// Two files end in util/util.h: the one sharing lib/ with the includer wins.
		{Module: "util/util.h", Name: quoted}:          {Local: "lib/include/util/util.h"},
		{Module: "/usr/include/stdio.h", Name: quoted}: {},
	} {
		if got := r.Resolve("lib/util.c", spec); got != want {
			t.Errorf("%s: got %+v, want %+v", spec.Module, got, want)
		}
	}
	if got := r.Resolve("src/main.cpp", lang.RawImport{Module: "util/util.h", Name: bracket}); got != external("util") {
		t.Errorf("an include two files end in, neither nearer: got %+v", got)
	}
}

// Verifies: REQ-CPP-004
func TestIncludeDirectories(t *testing.T) {
	for _, testCase := range []struct {
		arguments []string
		want      []string
	}{
		{[]string{"g++", "-Ia", "-I", "b", "-iquote", "c", "-isystem=d", "-idirafter", "e", "-include", "f.h", "/Ix"}, []string{"a", "b", "c", "=d", "e"}},
		{[]string{`C:\VS\bin\cl.exe`, "/Ia", "/I", "b", "/external:Ic", "-Id"}, []string{"a", "b", "c", "d"}},
	} {
		if got := includeDirectories(testCase.arguments); !reflect.DeepEqual(got, testCase.want) {
			t.Errorf("%v: got %v, want %v", testCase.arguments, got, testCase.want)
		}
	}
}

// Verifies: REQ-CPP-002, REQ-CPP-007
func TestPreprocess(t *testing.T) {
	source := strings.Join([]string{
		`#include "a.h" /* a comment "with quotes" */`,
		`char *s = "/* not a comment";`,
		`#include <b.h>`,
		`#if 0 // off`,
		`#include "c.h"`,
		`#elif defined(X)`,
		`#include "d.h"`,
		`#endif`,
		`#define LONG \`,
		`  #include "e.h"`,
		`#include_next <f.h>`,
		`#import <Foundation/Foundation.h>`,
	}, "\n")
	includes, dead := preprocess([]byte(source))
	var got []string
	for _, rawImport := range includes {
		got = append(got, rawImport.Spec)
	}
	want := []string{`#include "a.h"`, `#include <b.h>`, `#include "d.h"`, `#include_next <f.h>`}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("includes: got %q, want %q", got, want)
	}
	if !dead[5] || dead[7] || dead[3] {
		t.Errorf("dead lines: %v", dead)
	}
}

// Verifies: REQ-CPP-003
func TestSymbols(t *testing.T) {
	results := analyze(t)
	langtest.CheckSymbols(t, results["include/app/app.hpp"], map[string]string{
		"APP_VERSION": "macro", "APP_MAX": "macro", "app": "namespace",
		"Server": "class", "Server.Server": "method", "Server.~Server": "method", "Server.start": "method",
		"Server.port": "method", "Server.operator==": "method", "Server.Options": "struct",
		"Mode": "enum", "Value": "union", "Name": "type", "Id": "type", "twice": "func", "parse": "func",
	})
	// Out-of-class definitions belong to their class; a prototype of a function the
	// file defines is not a second symbol; nothing in a function body or #if 0 is one,
	// nor a test macro's body.
	langtest.CheckSymbols(t, results["src/main.cpp"], map[string]string{
		"ALIVE": "macro", "app": "namespace", "Server.Server": "method", "Server.~Server": "method",
		"Server.start": "method", "helper": "func", "Point": "struct", "callback_t": "type", "main": "func",
	})
	langtest.CheckSymbols(t, results["include/app/detail.hpp"], map[string]string{"app.detail": "namespace", "answer": "func"})
	// C with the C grammar, where "new" is a name.
	langtest.CheckSymbols(t, results["lib/util.c"], map[string]string{"buffer": "struct", "split": "func", "util_count": "func"})
	// A C header read by the C++ grammar; its guard is no symbol.
	langtest.CheckSymbols(t, results["lib/include/util/util.h"], map[string]string{
		"util_list": "struct", "util_list_t": "type", "util_count": "func",
	})
}

// Verifies: REQ-CPP-001
func TestClaims(t *testing.T) {
	results := analyze(t)
	for _, p := range []string{"src/main.cpp", "lib/util.c", "include/app/app.hpp", "tests/stdio.h"} {
		if results[p] == nil {
			t.Errorf("%s not analyzed", p)
		}
	}
	if results["build/compile_commands.json"] != nil {
		t.Error("compile_commands.json analyzed")
	}
}

// Verifies: REQ-CPP-005
func TestStandard(t *testing.T) {
	for name, want := range map[string]string{
		"vector": ecosystemCppStd, "cstdio": ecosystemCppStd, "experimental/filesystem": ecosystemCppStd, "bits/stdc++.h": ecosystemCppStd,
		"stdio.h": ecosystemCStd, "threads.h": ecosystemCStd, "unistd.h": ecosystemSystem, "sys/types.h": ecosystemSystem,
		"linux/fs.h": ecosystemSystem, "Windows.h": ecosystemSystem, "TargetConditionals.h": ecosystemSystem, "ext/stdio_filebuf.h": ecosystemCppStd, "CoreFoundation/CoreFoundation.h": ecosystemSystem, "immintrin.h": ecosystemSystem,
		"boost/asio.hpp": "", "curl/curl.h": "", "vector.h": "",
	} {
		if got := standard(name); got != want {
			t.Errorf("%s: got %q, want %q", name, got, want)
		}
	}
}

// symbolsOf extracts source as a file with the given extension.
func symbolsOf(t *testing.T, extension, source string) map[string]string {
	t.Helper()
	extraction, err := Plugin{}.Extract(&scan.File{Path: "x" + extension}, []byte(source))
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]string{}
	for _, s := range extraction.Symbols {
		got[s.Name] = s.Kind
	}
	return got
}

// The scanner's reading of constructs a declaration scanner can get wrong; each
// case was found comparing it with the tree-sitter grammars it replaced.
//
// Verifies: REQ-CPP-003, REQ-CPP-014
func TestScanner(t *testing.T) {
	// cSpell: disable
	for _, testCase := range []struct {
		name, extension, source string
		want                    map[string]string
	}{
		{"macro lines before a namespace", ".h", "namespace absl {\nABSL_NAMESPACE_BEGIN\nnamespace internal {\nint f();\n}\nABSL_NAMESPACE_END\n}\n",
			map[string]string{"absl": "namespace", "internal": "namespace", "f": "func"}},
		{"export macro and bases", ".hpp", "class API_EXPORT Widget final : public Base<int>, private Other {\n public:\n  Widget() : a_{1}, b_(2) {}\n  ~Widget() override = default;\n  Q_OBJECT\n public slots:\n  void onClick();\n};\n",
			map[string]string{"Widget": "class", "Widget.Widget": "method", "Widget.~Widget": "method", "Widget.onClick": "method"}},
		{"operators", ".hpp", "struct V {\n  bool operator==(const V&) const;\n  int operator()(int) const { return 0; }\n  explicit operator bool() const { return true; }\n};\nV operator\"\"_v(unsigned long long);\ntemplate <class T> Box<T>& Box<T>::operator=(const Box&) { return *this; }\n",
			map[string]string{"V": "struct", "V.operator==": "method", "V.operator()": "method", "operator\"\"_v": "func", "Box.operator=": "method"}},
		{"variables are not functions", ".cc", "std::atomic<Tracker*> g_tracker(nullptr);\nstatic Foo g_foo(1, 2);\nstruct stat st;\nauto cb = [](int x) { return x; };\nconst Options kDefaults = Options().WithDomains(Arbitrary());\nint real(int x);\n",
			map[string]string{"real": "func"}},
		{"function heads in #if branches", ".c", "#ifdef WIN32\nint open_file(const wchar_t *p) {\n#else\nint open_file(const char *p) {\n#endif\n  return 0;\n}\nint after(void) { return 1; }\n",
			map[string]string{"open_file": "func", "after": "func"}},
		{"extern C and typedefs", ".h", "#ifdef __cplusplus\nextern \"C\" {\n#endif\ntypedef double(BigOFunc)(int);\ntypedef struct { int x; } point_t, *point_p;\ntypedef enum color { RED } color_t;\ntypedef std::map<int, int> Map;\nstruct vtable {\n  void (*destroy)(void*);\n};\n#ifdef __cplusplus\n}\n#endif\n",
			map[string]string{"BigOFunc": "type", "point_t": "type", "point_p": "type", "color": "enum", "color_t": "type", "Map": "type", "vtable": "struct", "vtable.(*destroy)": "method"}},
		{"macro-made names and test macros", ".c", "UPB_INLINE bool UPB_PRIVATE(_upb_IsPrint)(unsigned char ch) { return ch > 31; }\nTEST(Suite, Case) { }\nDEFINE_flag(verbose);\n",
			map[string]string{"UPB_PRIVATE(_upb_IsPrint)": "func"}},
		{"C names that are C++ keywords", ".c", "struct list *new(int class) { return 0; }\nint delete_all(struct list *new) { return 0; }\n",
			map[string]string{"new": "func", "delete_all": "func"}},
		{"trailing return and templates", ".hpp", "namespace a::b {\ntemplate <typename T, typename = std::enable_if_t<(sizeof(T) > 4)>>\nauto twice(T v) -> decltype(v + v) { return v + v; }\nusing Id = std::uint64_t;\nenum class Mode : std::uint8_t { Fast, Safe };\n}\n",
			map[string]string{"a.b": "namespace", "twice": "func", "Id": "type", "Mode": "enum"}},
		{"defines", ".h", "#ifndef GUARD_H\n#define GUARD_H\n#define ON\n#define MAX(a, b) ((a) > (b) ? (a) : (b))\nvoid f() {\n#define LOCAL 1\n}\n#endif\n",
			map[string]string{"ON": "macro", "MAX": "macro", "f": "func"}},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			if got := symbolsOf(t, testCase.extension, testCase.source); !reflect.DeepEqual(got, testCase.want) {
				t.Errorf("got %v, want %v", got, testCase.want)
			}
		})
	}
	// cSpell: enable
}

// A generated descriptor table, a long initializer of character literals, is
// stepped over in one pass: the C grammar needed more than the 3 s parse bound
// for each of 79 such files in grpc.
//
// Verifies: REQ-CPP-014
func TestGeneratedTables(t *testing.T) {
	var b strings.Builder
	b.WriteString("#include \"upb/reflection/def.h\"\nstatic const char descriptor[200000] = {\n")
	for i := 0; i < 200000; i++ {
		b.WriteString("'\\036', 'a', ")
	}
	b.WriteString("\n};\n_upb_DefPool_Init init = {deps, &layout, \"x.proto\"};\nconst upb_MessageDef* x_getmsgdef(upb_DefPool* s) { return 0; }\n")
	start := time.Now()
	extraction, err := Plugin{}.Extract(&scan.File{Path: "x.upbdefs.c"}, []byte(b.String()))
	if err != nil || len(extraction.Imports) != 1 || len(extraction.Symbols) != 1 || extraction.Symbols[0].Name != "x_getmsgdef" {
		t.Fatalf("got %+v, %v", extraction, err)
	}
	if d := time.Since(start); d > langtest.TimeLimit(2*time.Second) {
		t.Errorf("took %v", d)
	}
}

// Extraction returns for any input: every prefix of the fixtures and runs of
// unfinished constructs.
//
// Verifies: REQ-CPP-014
func TestTruncated(t *testing.T) {
	var sources []string
	for _, p := range []string{"testdata/repo/src/main.cpp", "testdata/repo/include/app/app.hpp", "testdata/repo/lib/util.c"} {
		b, err := os.ReadFile(p)
		if err != nil {
			t.Fatal(err)
		}
		for i := range b {
			sources = append(sources, string(b[:i]))
		}
	}
	for _, run := range []string{"{", "}", "(", ")", "<", ">", "template<", "namespace a {", "class A {", "struct A : ",
		"operator", "::", "f(x)", "typedef ", "/*", "\"", "R\"x(", "'", "#if X\n", "#else\n", "#endif\n", "#define X \\\n",
		"extern \"C\" {", "A::A() : a(1), ", "auto f() -> a<", "enum class E : ", "FOO(x)\n", "~", "= {"} {
		sources = append(sources, strings.Repeat(run, 3000))
	}
	for _, source := range sources {
		for _, extension := range []string{".c", ".hpp"} {
			if _, err := (Plugin{}).Extract(&scan.File{Path: "x" + extension}, []byte(source)); err != nil {
				t.Fatal(err)
			}
		}
	}
}
