package cpp

import (
	"path"
	"strings"

	"github.com/sarumaj/depphunter-cli/internal/lang"
	"github.com/sarumaj/depphunter-cli/internal/scan"
)

// conventional are the directories an include is looked up in when nothing says
// where the project's headers are: include/ and src/ at the root, and the root.
var conventional = []string{"include", "src", ""}

type resolver struct {
	files  map[string]bool     // every project file
	byBase map[string][]string // file name -> the project files so named
	db     *compileDB
	pkgs   *packages // what vcpkg and Conan manifests declare
}

// Implements: REQ-CPP-004
func newResolver(root string, all []*scan.File) *resolver {
	r := &resolver{files: map[string]bool{}, byBase: map[string][]string{}, db: readCompileDB(root, all), pkgs: readPackages(all)}
	for _, f := range all {
		r.files[f.Path] = true
		base := path.Base(f.Path)
		r.byBase[base] = append(r.byBase[base], f.Path)
	}
	return r
}

// Resolve follows an include to a project file, a standard or system header, a
// package a vcpkg or Conan manifest declares, or else a third-party library.
//
// Implements: REQ-CPP-004, REQ-CPP-005, REQ-CPP-006, REQ-CPP-012
func (r *resolver) Resolve(file string, imp lang.RawImport) lang.Target {
	name := strings.ReplaceAll(imp.Module, `\`, "/")
	if name == "" || path.IsAbs(name) || (len(name) > 1 && name[1] == ':') {
		return lang.Target{} // an absolute path is this machine's, not the project's
	}
	std := standard(name)
	// The quoted form searches the includer's own directory first; both then search
	// the include path.
	var dirs []string
	if imp.Name == quoted {
		dirs = append(dirs, path.Dir(file))
	}
	dirs = append(dirs, r.db.dirs(file)...)
	// A project's own headers are often included with <>, and without a compilation
	// database where they live is guessed - but not for a standard or system header
	// included with <>, which a same-named file somewhere in the project does not
	// shadow. A quoted one ("net/socket.h") is the project's when it has one.
	if std == "" || imp.Name == quoted {
		dirs = append(dirs, conventional...)
	}
	for _, d := range dirs {
		if p := path.Join(d, name); r.files[p] && !strings.HasPrefix(p, "../") {
			return lang.Target{Local: p}
		}
	}
	if std == "" || imp.Name == quoted {
		if p := r.bySuffix(file, name); p != "" {
			return lang.Target{Local: p}
		}
	}
	if std != "" {
		return lang.Target{Ecosystem: std, Package: name}
	}
	// A quoted include of a bare name the project does not have is generated by the
	// build (config.h, version.h) or found outside the tree: nothing to name.
	if imp.Name == quoted && (!strings.Contains(name, "/") || strings.HasPrefix(name, ".")) {
		return lang.Target{}
	}
	if p := r.pkgs.match(file, name); p != nil {
		return p.target()
	}
	return lang.Target{Ecosystem: ecoExternal, Package: library(name), Unresolved: true}
}

// Dependencies implements lang.Transitive from a Conan 1 conan.lock's graph.
//
// Implements: REQ-CPP-011
func (r *resolver) Dependencies(t lang.Target) []lang.Target { return r.pkgs.Dependencies(t) }

// bySuffix finds the project file whose path ends in the include ("foo/bar.h" in
// libs/foo/bar.h): the only one, or else the one closest to the includer when that
// is closer than all the others.
func (r *resolver) bySuffix(file, name string) string {
	var best string
	bestLen, tie := -1, false
	for _, p := range r.byBase[path.Base(name)] {
		if p != name && !strings.HasSuffix(p, "/"+name) {
			continue
		}
		n := commonDirs(file, p)
		switch {
		case n > bestLen:
			best, bestLen, tie = p, n, false
		case n == bestLen:
			tie = true
		}
	}
	if tie {
		return ""
	}
	return best
}

// commonDirs counts the leading directories two paths share.
func commonDirs(a, b string) int {
	as, bs := strings.Split(path.Dir(a), "/"), strings.Split(path.Dir(b), "/")
	n := 0
	for n < len(as) && n < len(bs) && as[n] == bs[n] && as[n] != "." {
		n++
	}
	return n
}

// library names the third-party library an include belongs to: its first directory
// (<boost/asio.hpp> -> boost), or a bare header's name without its extension
// (<zlib.h> -> zlib).
func library(name string) string {
	if dir, _, ok := strings.Cut(name, "/"); ok {
		return dir
	}
	return strings.TrimSuffix(name, path.Ext(name))
}
