package cpp

import (
	"path"
	"strings"

	"github.com/sarumaj/depphunter-cli/internal/lang"
	"github.com/sarumaj/depphunter-cli/internal/scan"
	"github.com/sarumaj/depphunter-cli/internal/trace"
)

// conventional are the directories an include is looked up in when nothing says
// where the project's headers are: include/ and src/ at the root, and the root.
var conventional = []string{"include", "src", ""}

type resolver struct {
	files  map[string]bool     // every project file
	byBase map[string][]string // file name -> the project files so named
	db     *compileDB
	xcode  *xcodePaths
	pkgs   *packages // what vcpkg and Conan manifests declare
}

// The notes a resolver keeps reach --explain only through lang.Noter.
var _ lang.Noter = (*resolver)(nil)

// Implements: REQ-CPP-004
func newResolver(root string, all []*scan.File) *resolver {
	r := &resolver{files: map[string]bool{}, byBase: map[string][]string{}, db: readCompileDB(root, all), xcode: readXcode(all),
		pkgs: readPackages(all)}
	for _, f := range all {
		r.files[f.Path] = true
		base := path.Base(f.Path)
		r.byBase[base] = append(r.byBase[base], f.Path)
	}
	return r
}

// Resolve follows an include to a project file, a standard or system header, a
// header of a GPU toolkit or the Metal SDK, a package a vcpkg or Conan manifest
// declares, or else a third-party library.
//
// Implements: REQ-CPP-004, REQ-CPP-005, REQ-CPP-006, REQ-CPP-012, REQ-CPP-016
func (r *resolver) Resolve(file string, imp lang.RawImport) lang.Target {
	return r.resolve(file, imp, nil)
}

// Includes resolves includes as the cpp plugin does, for a plugin whose sources
// include C headers the same way but know more third-party headers (objc: CocoaPods).
type Includes struct{ r *resolver }

// NewIncludes reads what resolving includes needs: the file list, a compilation
// database, vcpkg and Conan manifests.
func NewIncludes(root string, all []*scan.File) Includes { return Includes{newResolver(root, all)} }

// Resolve is the cpp plugin's resolution, with external asked about a header that is
// neither the project's nor a standard, system or GPU toolkit header before it is
// dropped (a quoted bare name) or attributed to vcpkg, Conan or c-external.
//
// Implements: REQ-OBJC-004, REQ-SHADER-004
func (in Includes) Resolve(file string, imp lang.RawImport, external func(name string, quoted bool) (lang.Target, bool)) lang.Target {
	return in.r.resolve(file, imp, external)
}

// Library is Packages.Library over the project's vcpkg and Conan manifests.
func (in Includes) Library(file, include string) lang.Target {
	return Packages{in.r.pkgs}.Library(file, include)
}

func (r *resolver) resolve(file string, imp lang.RawImport, external func(name string, quoted bool) (lang.Target, bool)) lang.Target {
	name := strings.ReplaceAll(imp.Module, `\`, "/")
	if name == "" || path.IsAbs(name) || (len(name) > 1 && name[1] == ':') {
		return lang.Target{} // an absolute path is this machine's, not the project's
	}
	std := standard(name)
	// The quoted form searches the includer's own directory first; both then search
	// the include path.
	var dirs []string
	if imp.Name == quoted {
		dirs = append(dirs, path.Dir(file))
	}
	dirs = append(dirs, r.db.dirs(file)...)
	for _, directory := range dirs {
		if candidate := path.Join(directory, name); r.files[candidate] && !strings.HasPrefix(candidate, "../") {
			return lang.Target{Local: candidate}
		}
	}
	// Then an Xcode project's header search paths, which may search a whole tree.
	if found := r.xcode.find(file, name, r.files, r.byBase); found != "" {
		return lang.Target{Local: found}
	}
	// A project's own headers are often included with <>, and without a compilation
	// database where they live is guessed - but not for a standard or system header
	// included with <>, which a same-named file somewhere in the project does not
	// shadow. A quoted one ("net/socket.h") is the project's when it has one.
	if std == "" || imp.Name == quoted {
		for _, directory := range conventional {
			if candidate := path.Join(directory, name); r.files[candidate] && !strings.HasPrefix(candidate, "../") {
				return lang.Target{Local: candidate}
			}
		}
	}
	if std == "" || imp.Name == quoted {
		if p := r.bySuffix(file, name); p != "" {
			return lang.Target{Local: p}
		}
	}
	if std != "" {
		return lang.Target{Ecosystem: std, Package: name}
	}
	if t, ok := sdk(name); ok {
		return t
	}
	if external != nil {
		if t, ok := external(name, imp.Name == quoted); ok {
			return t
		}
	}
	// A quoted include of a bare name the project does not have is generated by the
	// build (config.h, version.h) or found outside the tree: nothing to name.
	if imp.Name == quoted && (!strings.Contains(name, "/") || strings.HasPrefix(name, ".")) {
		return lang.Target{}
	}
	return Packages{r.pkgs}.Library(file, name)
}

// Dependencies implements lang.Transitive from a Conan 1 conan.lock's graph.
//
// Implements: REQ-CPP-011
func (r *resolver) Dependencies(t lang.Target) []lang.Target { return r.pkgs.Dependencies(t) }

// Notes implements lang.Noter: a Conan 2 lock pins versions and records no edges,
// and nothing past it is asked of any index either.
//
// Implements: REQ-CPP-011, REQ-TRC-017
func (r *resolver) Notes() []trace.Note {
	var out []trace.Note
	for _, f := range r.pkgs.flat {
		out = append(out, trace.Note{File: f, Code: trace.NoteFlat, Message: "a Conan 2 lock pins versions but " +
			"records no edges, and no index is asked for Conan: --resolve-depth adds nothing past the packages it pins"})
	}
	return out
}

// bySuffix finds the project file whose path ends in the include ("foo/bar.h" in
// libs/foo/bar.h): the only one, or else the one closest to the includer when that
// is closer than all the others.
func (r *resolver) bySuffix(file, name string) string {
	var best string
	bestLen, tie := -1, false
	for _, p := range r.byBase[path.Base(name)] {
		if p != name && !strings.HasSuffix(p, "/"+name) {
			continue
		}
		n := commonDirs(file, p)
		switch {
		case n > bestLen:
			best, bestLen, tie = p, n, false
		case n == bestLen:
			tie = true
		}
	}
	if tie {
		return ""
	}
	return best
}

// commonDirs counts the leading directories two paths share.
func commonDirs(a, b string) int {
	as, bs := strings.Split(path.Dir(a), "/"), strings.Split(path.Dir(b), "/")
	n := 0
	for n < len(as) && n < len(bs) && as[n] == bs[n] && as[n] != "." {
		n++
	}
	return n
}

// library names the third-party library an include belongs to: its first directory
// (<boost/asio.hpp> -> boost), or a bare header's name without its extension
// (<zlib.h> -> zlib).
func library(name string) string {
	if dir, _, ok := strings.Cut(name, "/"); ok {
		return dir
	}
	return strings.TrimSuffix(name, path.Ext(name))
}
